name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Git identity (optional, only if you commit locally in Actions)
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 3. Pull latest changes from main (keeps runner in sync)
      - name: Git Pull
        run: git pull origin main

      # 4. Example build step (replace with your actual build commands)
      - name: Example Build Step
        run: echo "Build commands go here"

      # 5. Deploy via SFTP (recommended)
      - name: Upload to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          protocol: ftp   # change to ftp if your server doesn’t support sftp
          server-dir: ${{ secrets.DIR }}
          log-level: verbose
