name: UPLOADING

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    Server-Upload:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Install SSH Client and sshpass
             uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  with:
    server: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    password: ${{ secrets.PASSWORD }}
    port: 21
    protocol: ftp
    server-dir: ${{ secrets.DIR }}
    state-name: .ftp-deploy-sync-state.json
    dangerous-clean-slate: true
    log-level: verbose
    exclude: |
      **/.git*
      **/.github*